---
- hosts: all

  become: yes
  tasks:

  - name: download foundry
    shell: curl {{ foundry_url }} --output /tmp/foundryvtt.zip

  - name: unzip folder
    unarchive:
      src: /tmp/foundryvtt.zip
      dest: /opt/foundryvtt
      remote_src: yes
  
  - name: install node
    apt:
      name:
        - nodejs
    update_cache: yes

  - name: install pm2
    npm:
      name: pm2
      global: true
      state: present

  - name: make directory
    file:
      path: /opt/foundrydata
      state: directory
      mode: '0755'
  
  - name: start foundry
    shell: pm2 start node --name foundry -- /home/ubuntu/foundryvtt/resources/app/main.js --dataPath=/home/ubuntu/foundrydata