---
- hosts: all

  become: yes
  tasks:
  
  #Disable Apache
  - name: disable apache
    systemd:
      name: apache2
      state: stop
      enabled: false

  #Install PHP8
  - name: install php8
    apt:
      name:
        - php8.1
      update_cache: yes

  #Install php-fpm
  - name: install php-fpm
    apt:
      name:
        - php8.1-fpm
        - php8.1-mbstring
        - php8.1-yaml
      update_cache: yes

  #Install dependancies
  - name: install dependancies
    apt:
      name:
        - git
        - nginx
      update_cache: yes
