---
- hosts: perlite
  vars:
    INSTALL: false
    foundry_url: ""

  become: yes
  tasks:
  - name: install node
    apt:
      name:
        - nodejs
    when: INSTALL

  - name: install pm2
    npm:
      name: pm2
      global: true
      state: present
    when: INSTALL
    
  - name: make directory
    file:
      path: /opt/foundrydata
      state: directory
      mode: '0755'
    when: INSTALL

  - name: stop foundry
    shell: pm2 stop node --name foundry
    when: not INSTALL

  - name: download foundry
    shell: curl {{ foundry_url }} --output /tmp/foundryvtt.zip

  - name: unzip folder
    unarchive:
      src: /tmp/foundryvtt.zip
      dest: /opt/foundryvtt
      remote_src: yes

  - name: start foundry
    shell: pm2 start node --name foundry -- /home/ubuntu/foundryvtt/resources/app/main.js --dataPath=/home/ubuntu/foundrydata