---
- hosts: all:!192.168.1.67
  become: true

  # Install Wazuh Agent
  tasks:
    - name: add wazuh gpg key
      ansible.builtin.shell:
        cmd: curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | gpg --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/wazuh.gpg --import && chmod 644 /usr/share/keyrings/wazuh.gpg

    - name: add wazuh repo
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main
        state: present
    
    - name: install wazuh
      shell: WAZUH_MANAGER="{{ lookup('env','WAZUH_MANAGER') }}" apt-get install wazuh-agent

    - name: start wazuh agent
      ansible.builtin.systemd:
        daemon-reload: true
        state: started
        enabled: true
        name: wazuh-agent
      
    - name: disable Wazuh repo
      ansible.builtin.shell:
        cmd: sudo echo "wazuh-agent hold" | dpkg --set-selections
      